### ISSUE TITLE
1.1.2 gem not updated at rubygems

### ISSUE THREAD

**Issue by bobbywilson0** [tokumine/GData#3]
I have installed 1.1.2 from rubygems but it doesn't include the 1.9.x jcode fix. Has this version been released multiple times? Would you be willing to bump the version and release again as 1.1.3 to get the gem to propogate properly?

**Comment by tokumine** [comment]
Hi there - the jcode fix has been in since the start (kinda the main reason for releasing this patch :)).

Can I just confirm that you are using the http://rubygems.org/gems/gdata_19 gem? (note the underscore).

Thanks!

**Comment by bobbywilson0** [comment]
Hey @tokumine,

You're right! I didn't know that gdata_19 was what I needed to install. What is the reason to rename the gem in this case? With the condition around the jcode stuff it seems like it wouldn't affect ruby < 1.8. The reason I am asking is because gems that have gdata as a dep will now all need to switch the gem name to be ruby 1.9.x compatible.

**Comment by tokumine** [comment]
This gem does work with 1.8 and 1.9, you're right.  The name is gdata_19 as it is not the 'official' gdata gem (which is still stuck on 1.8 only right now

The problems with dependency management is one that is not lost on me believe me!  The best I can suggest is to collaborate in their migration or make your own fork (I know, not what you wanted to hear...)
